[package]
name = "beacon-core"
version.workspace = true
edition.workspace = true

[dependencies]
miette.workspace = true
tokio = { workspace = true, features = ["net", "signal"] }
tokio-util.workspace = true

[lints]
workspace = true
