[package]
name = "beacon"
version.workspace = true
edition.workspace = true

[dependencies]
beacon-core = { path = "../beacon-core" }
miette = "7.6.0"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros"] }

[lints]
workspace = true
