[package]
name = "beacon-config"
version.workspace = true
edition.workspace = true

[dependencies]
bevy_ecs.workspace = true
figment = { workspace = true, features = ["toml"] }
serde = { workspace = true, features = ["derive"] }

[lints]
workspace = true
