[package]
name = "beacon-net"
version.workspace = true
edition.workspace = true

[dependencies]
beacon-codec.workspace = true
bytes.workspace = true
tokio = { workspace = true, features = ["io-util"] }

[lints]
workspace = true
